[[questions]]
id = "RN021"
question = "När föreslås träda i kraft?"
answer = "1 juli 2024"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [9]

[[questions]]
id = "RN022"
question = "När beslutade regeringen att inhämta Lagrådets yttrande över lagförslaget?"
answer = "Den 22 juni 2023"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [5]

[[questions]]
id = "RN023"
question = "Vad var syftet med Läromedelsutredningen som tillsattes 2019?"
answer = "Den socialdemokratiskt ledda regeringen tillsatte 2019 en utredning med uppdrag att bl.a. föreslå hur statens roll bör se ut när det gäller läromedel i svensk skola"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [29]

[[questions]]
id = "RN024"
question = "Vad anser undertecknarna är angeläget att regeringen fortsätter med?"
answer = "Vi anser att det är angeläget att regeringen fortsätter arbetet för att säkerställa en god och likvärdig tillgång till läromedel av hög kvalitet på alla skolor"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [29]

[[questions]]
id = "RN025"
question = "Vad föreslår regeringen att skollagen ska kompletteras med?"
answer = "I propositionen föreslår regeringen att skollagen ska kompletteras med definitioner av begreppen lärobok, läromedel och lärverktyg"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [17]


[[questions]]
id = "RN026"
question = "Vilka skolformer omfattas av kravet att elever ska ha tillgång till läroböcker, läromedel och lärverktyg?"
answer = "Sammantaget föreslår regeringen att det i skollagen ska anges att elever i förskoleklassen, grundskolan, anpassade grundskolan, specialskolan, sameskolan, gymnasieskolan och anpassade gymnasieskolan ska ha tillgång till läroböcker, andra läromedel och andra lärverktyg som behövs för en god kunskapsutveckling i enlighet med utbildningens mål"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [17]

[[questions]]
id = "RN027"
question = "Vad är läromedlens främsta funktion enligt regeringen?"
answer = "Regeringen anför att därigenom betonas att lärverktygens främsta funktion är att stärka elevers kunskapsutveckling och vikten av att läromedel och övriga lärverktyg förhåller sig till aktuell kurs-, ämnes- eller ämnesområdesplan, läroplanen och till bestämmelser om mål för utbildningen i skollagen"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [17]


[[questions]]
id = "RN028"
question = "Vad vill motionärerna bakom kommittémotion 2023/24:2755 att regeringen ska göra?"
answer = "I kommittémotion 2023/24:2755 yrkande 3 föreslår Åsa Westlund m.fl. (S) ett tillkännagivande till regeringen om att stärka tillgången av läromedel inom den kommunala vuxenutbildningen"
difficulty = "Easy"
category = "Education"

[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [16]

[[questions]]
id = "RN029"
question = "Vad föreslår kommittémotion 2023/24:2753 (V)?"
answer = "I kommittémotion 2023/24:2753 yrkande 2 föreslår Daniel Riazat m.fl. (V) ett tillkännagivande om att regeringen bör tillsätta en utredning som undersöker att det finns relevanta tryckta läromedel som följer ämnenas fastställda kursplaner"
difficulty = "Easy"
category = "Education"

[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [16]


[[questions]]
id = "RN030"
question = "Vad anser regeringen är viktigt när det gäller användning av undervisningsmaterial?"
answer = "Regeringen anför bl.a. att det är viktigt att sträva mot en balans mellan olika undervisningsmaterial som t.ex. läroböcker, andra läromedel, fack- och skönlitteratur, olika former av autentiska texter, digitala presentationer, film, material för skapande, laborationsutrustning och annan utrustning"
difficulty = "Easy"
category = "Education"

[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [13]

[[questions]]
id = "RN031"
question = "Hur vill regeringen att en lärobok ska definieras i skollagen?"
answer = "Regeringen föreslår att en lärobok ska definieras som ett tryckt läromedel, med eller utan digitala komponenter"
difficulty = "Easy"
category = "Education"

[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [11]

[[questions]]
id = "RN032"
question = "Vad säger regeringen om tryckta läromedels roll i undervisningen?"
answer = "Regeringen anför i propositionen att tryckta läromedel har en given plats i undervisningen och kan kombineras med, men inte ersättas av, digitala läromedel"
difficulty = "Easy"
category = "Education"

[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [11]


[[questions]]
id = "RN033"
question = "Varför vill regeringen införa fler definitioner i skollagen?"
answer = " För att en uppdaterad reglering ska bli tydlig är det dock viktigt att även de begrepp som används i sådana bestämmelser är tydliga. Regeringen anser att det behövs definitioner av såväl lärverktyg som läromedel och läroböcker"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [9]

[[questions]]
id = "RN034"
question = "Vilka begrepp föreslås få en tydlig definition i skollagen enligt regeringen?"
answer = "Regeringen anser att det behövs definitioner av såväl lärverktyg som läromedel och läroböcker"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [9]

[[questions]]
id = "RN035"
question = "Vad har elever i förskoleklass till anpassad gymnasieskola rätt till utan kostnad?"
answer = "Elever som går i förskoleklassen, grundskolan, anpassade grundskolan, specialskolan, sameskolan och anpassade gymnasieskolan ska utan kostnad ha tillgång till böcker och andra lärverktyg som behövs för en tidsenlig utbildning"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [8]

[[questions]]
id = "RN036"
question = "Vad gäller för elever i komvux när det gäller att bekosta läromedel?"
answer = "Inom komvux på grundläggande och gymnasial nivå samt inom komvux som anpassad utbildning på grundläggande och gymnasial nivå får huvudmannen bestämma att böcker och andra lärverktyg som eleverna har för eget bruk och får behålla som sin egendom ska anskaffas av eleverna själva eller erbjudas mot avgifter som högst motsvarar huvudmannens anskaffningskostnader"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [8]

[[questions]]
id = "RN037"
question = "Vilket uttryck vill regeringen ersätta i skollagen?"
answer = "Regeringen föreslår därför att ”tidsenlig utbildning” ersätts med ”god kunskapsutveckling i enlighet med utbildningens mål”"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [13]


[[questions]]
id = "RN038"
question = "Varför vill regeringen ersätta uttrycket 'tidsenlig utbildning'?"
answer = "Regeringen delar denna uppfattning, men anser att bestämmelsen bör tydliggöras ytterligare. Regeringen föreslår därför att ”tidsenlig utbildning” ersätts med ”god kunskapsutveckling i enlighet med utbildningens mål”"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [13]

[[questions]]
id = "RN039"
question = "Vad föreslår regeringen om terminologin för komvux jämfört med andra skolformer?"
answer = "Regeringen anser att det inte hindrar att terminologin i de olika bestämmelserna om vad eleverna i de olika skolformerna ska ha tillgång till bör vara densamma"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [14]


[[questions]]
id = "RN040"
question = "Vad är syftet med att dela upp 20 kap. 7 § i flera paragrafer?"
answer = "De redaktionella ändringar som föreslås innebär att 20 kap. 7 § delas upp i tre paragrafer (20 kap. 7–7 b §§) för att lagtexten ska bli mer lättläst"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "2023_24_UbU6_20231211104325_Publicering.pdf"
page_numbers = [14]
