[[questions]]
id = "RN081"
question = "Vem hade högsta ansvar för den svenska kolonin under dess sista år?"
answer = " Därmed tilldelades han högsta ansvar för kolonin under de sista åren av dess existens"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [28]

[[questions]]
id = "RN082"
question = "Vilken titel fick Erik Oxenstierna år 1652?"
answer = "Erik fick titeln generaldirektör i Kommerskollegium år 1652"
difficulty = "Medium"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [28]

[[questions]]
id = "RN083"
question = "Vad ska Kapten Amundson sträva efter i relation till grannländer?"
answer = "Du ska sträva efter att upprätthålla goda relationer och korrespondens med grannländerna Holland och England, utan att störa deras rättigheter"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [25]


[[questions]]
id = "RN084"
question = "Vad hette skeppet som Per Lindeström reste med till Nya Sverige?"
answer = "Lindeström anlände till Nya Sverige efter Guvernör Printz avgått med skeppet Örnen tillsammans med den siste guvernören Johan Rising"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [31]

[[questions]]
id = "RN085"
question = "Vad uppmanade Axel Oxenstierna sin son Erik att göra?"
answer = "Oxenstierna uppmanar sin son till att skriva om mer kring Nya Sverige och om den nya guvernören Johan Rising"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [29]

[[questions]]
id = "RN086"
question = "Vilken position hade kapten Hans Amundson i Nya Sverige?"
answer = "Amundsons nya position som överkommendör i Nya Sverige"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [25]

[[questions]]
id = "RN087"
question = "Vad var en av orsakerna till att kolonin fick namnet 'Myggeborg'?"
answer = "Detta berodde på att myggor spred sjukdomar i området vilket orsakade att skansen döptes om till Myggeborg"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [33]

[[questions]]
id = "RN088"
question = "Vilken sjukdom kopplade Lindeström till djävulsbesvärjaren?"
answer = "den sexuella sjukdomen, syfilis"
difficulty = "Medium"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [35]

[[questions]]
id = "RN089"
question = "Varför skulle brottslingar inte få nåd i kolonin enligt Oxenstiernas instruktioner?"
answer = "bör man inte visa någon nåd mot brottslingarna, utan i stället genomföra en ordentlig rättegång med de nämnda personerna som vittnen och omedelbart verkställa den dom som har avkunnats mot dem"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [27]

[[questions]]
id = "RN090"
question = "Vad var Per Lindeströms yrke i Nya Sverige"
answer = "Han hade en viktig betydelse i att kartlägga landet och satte fästningsverk i bättre skick då han var utbildad fortifikationsingenjör"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [31]

[[questions]]
id = "RN091"
question = "Vilken grupp skulle inte tas med till Nya Sverige enligt Oxenstiernas instruktioner?"
answer = "Det onödiga folket, som inte ger kompaniet någon nytta utan endast söker nöje med resan, bör inte medtas"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [25]

[[questions]]
id = "RN092"
question = "Vad skulle Kapten Amundson sträva efter i relation till Holland och England?"
answer = "Du ska sträva efter att upprätthålla goda relationer och korrespondens med grannländerna Holland och England, utan att störa deras rättigheter"
difficulty = "Medium"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [25]

[[questions]]
id = "RN093"
question = "Varför var män mer eftertraktade än kvinnor för Nya Sverige?"
answer = "Fokus låg specifikt på att kunna försvara den nya kolonin"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [25]

[[questions]]
id = "RN094"
question = "Hur framställs religionens roll i Nya Sverige enligt Oxenstierna?"
answer = "Den lutherska tron, som inte bara var en religiös grundpelare utan även en grund för den goda självbild"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [28]

[[questions]]
id = "RN095"
question = "Vad hände med Nya Sverige efter Printz avgång och bristande relationer med holländarna?"
answer = "Holländarna kom att annektera Nya Sverige fem år senare efter första kriget mellan England och Holland"
difficulty = "Medium"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [26]

[[questions]]
id = "RN096"
question = "Hur kopplas begreppet ethnie till religionen i Nya Sverige?"
answer = "Återigen kan Smiths begrepp ethnie appliceras i att det var en prioritering att den svenska religionen skulle verka i det land Sverige hade monopol i"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [26]

[[questions]]
id = "RN097"
question = "Varför skulle det inte visas nåd mot brottslingar i Nya Sverige?"
answer = "bör man inte visa någon nåd mot brottslingarna, utan i stället genomföra en ordentlig rättegång med de nämnda personerna som vittnen och omedelbart verkställa den dom som har avkunnats mot dem"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [27]

[[questions]]
id = "RN098"
question = "Vilken roll spelade den lutherska tron i att forma den svenska nationella identiteten i Nya Sverige enligt Oxenstiernas instruktioner?"
answer = "En central aspekt var den lutherska tron, som inte bara var en religiös grundpelare utan även en grund för den goda självbild som det svenska elitskiktet önskade att förmedla. Den lutherska traditionen, som betonade dygd, ansvar och moral, bidrog till en nationell identitet som präglades av dessa värderingar. Oxenstiernas instruktioner speglar ett behov av att stärka och säkra den svenska identiteten i en utmanande och osäker kolonial kontext"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [28]

[[questions]]
id = "RN099"
question = "Vilket syfte hade den stränga straffskalan i kolonin enligt Oxenstierna?"
answer = "Detta har delvis en religiös prägel då kristna ej skulle begå brott på varandra utan orsak men även en prägel på den svenska identiteten"
difficulty = "Hard"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [27]

[[questions]]
id = "RN100"
question = "Hur särskilde svenskarna sig från andra kolonialmakter enligt instruktionerna till Amundson?"
answer = "Dessa egenskaper särskilde dem från andra kolonialmakter"
difficulty = "Easy"
category = "Education"
[[questions.files]]
file = "Den svenska kolonialmaktens betydelse.pdf"
page_numbers = [28]
